### ISSUE TITLE
URL is broken

### ISSUE THREAD

**Issue by Cyburstud** [argyleink/gui-toast#1]
The URL associated with this repository is broken. 

https://stackblitz.com/edit/node-jye68f

![image](https://user-images.githubusercontent.com/77064515/159972920-356be5b5-ac3a-46ae-968c-514e5353ec8e.png)

**Comment by argyleink** [comment]
wow, ty, this repo must have been accidentally created from stack blitz. will remove it!

here is the toast post that has links to src, demos and the youtube video https://web.dev/building-a-toast-component/
